---
- hosts: abcz
  become: true
  become_user: root
  tasks:
    - name: Executing of Pre-Validation Scripts
      script: /home/sverma/ansible/nwr/prevalidation/prevalid_scr.sh
      register: output
    - name: Fetching the Inventory Report
      fetch:
       src: /tmp/details.txt
       dest: /home/sverma/ansible/nwr/prevalidation/details/prevalidation-{{ inventory_hostname }}
       flat: yes
    - debug:
       msg: "Pre-validation reports has been copied to /home/sverma/ansible/nwr/prevalidation/details" 
